language: php

services:
  - mysql
php:
  - 5.6

before_install:
  - cp .env.travis .env
  - composer require satooshi/php-coveralls:dev-master
  - composer install --dev --ignore-platform-reqs
  - php artisan key:generate
  - mysql -e 'CREATE DATABASE zeal_db;'
  - php artisan migrate
  - php artisan db:seed

script:
  - mkdir -p build/logs
  - php vendor/bin/phpcbf --standard=ruleset.xml app
  - php vendor/bin/phpcs --standard=ruleset.xml app
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v